
lang: en-US
theme: jekyll-theme-minima
remote_theme: jekyll/minima
title: Ray Kooyenga (org) Github Pages
author: 
  name: Ray Kooyenga
  email: gmc5oz4k7@mozmail.com
baseurl: ""
url: "https://rkooyenga.github.io"
  name: rkooyenga.github.io
  twitter: 
  picture:
twitter_username: rayktweets
github_username: rkooyenga
logo: https://avatars.githubusercontent.com/u/9654073?s=400&u=9337cc5310e21fb81fe9bf48601240aee6c47e5d&v=4 # path of site logo, e.g. "/assets/images/logo.jpeg"

remote_theme: jekyll/minima

links_to_prev_next: true

minima:
  skin: classic
  date_format: "%a, %b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/rkooyenga/" }
    - { platform: twitter, user_url: "https://twitter.com/rayktweets/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@raykooyenga/" }
#    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ray???/" }

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tagging-related_posts
  - jekyll-target-blank
  - jekyll-postfiles
  - jekyll-og-image
#  - jekyll-pwa-plugin
  
tagline: blog about life and code and stuff
github_edit_url: "https://github.com/rkooyenga/rkooyenga.github.io/blob/master/"

feed:
  posts_limit: 1000

permalink: "/:title"

#pwa:
#  enabled: true # Optional
#  sw_src_filepath: service-worker.js # Optional
#  sw_dest_filename: service-worker.js # Optional
#  dest_js_directory: assets/js # Required
#  precache_recent_posts_num: 5 # Optional
#  precache_glob_directory: / # Optional
 # precache_glob_patterns: # Optional
  #  - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
  #  - index.html
  # precache_glob_ignores: # Optional
   # - sw-register.js
   # - "fonts/**/*"

og_image:
  output_dir: "assets/images/og"
#  image: "/assets/image"
#  domain: "rkooyenga.github.io"
  border_bottom:
    width: 20
    fill:
#      - "#820C02"
#      - "#A91401"
#      - "#D51F06"
#      - "#DE3F24"
#      - "#EDA895"

tag_page_layout: tag_page
tag_page_dir: tag
ignored_tags: [tags,to,ignore]
