lang: en-US
theme: jekyll-theme-minima
title: Ray Kooyenga (org) Github Pages
author: Ray Kooyenga
  name: rkooyenga.github.io
  email: gmc5oz4k7@mozmail.com
baseurl: / # /the optional subpath of your site, e.g. "/blog"
url: https://rkooyenga.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
  name: rkooyenga.github.io
  twitter: 
  picture:
twitter_username: rayktweets
github_username: rkooyenga
logo: https://avatars.githubusercontent.com/u/9654073?s=400&u=9337cc5310e21fb81fe9bf48601240aee6c47e5d&v=4 # path of site logo, e.g. "/assets/images/logo.png"

# Build settings
markdown: kramdown
theme: jekyll-theme-minima
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-admin
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
