github: [metadata]
encoding: UTF-8

remote_theme: deadflowers/jekyll-theme-basically-basic

lang: en-US
description: an area for notes and projects
title: ray kooyenga
baseurl: ''
url: https://rkooyenga.github.io
permalink: pretty
skin: raykooyenga

# Site Author
author: 
  name: Ray Kooyenga
  twitter: @rayktweets
  url: https://raykooyenga.com
  email: gmc5oz4k7@mozmail.com
  picture: //avatars.githubusercontent.com/u/9654073
twitter_username: rayktweets
github_username: rkooyenga
logo: https://avatars.githubusercontent.com/u/6174603

email: gmc5oz4k7@mozmail.com

links:
    - title: Twitter
      url: https://x.com/rayktweets
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/raykooyenga
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/rkooyenga
      icon: fab fa-github-square

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-pwa-plugin
#  - jekyll-admin
  - jekyll-tagging-related_posts
  - jekyll-target-blank
  - jekyll-postfiles
#  - jekyll-og-image

feed:
  path: feed.xml
  
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
    
# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs 
  - /example
  - /archive
  - /fonts
  
# Collections
collections:
  gists:
    output: true
    permalink: /:collection/:path/
    
# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      # _gists
  - scope:
      path: "_gists"
      type: gists
    values:
      layout: post
      read_time: true
